config/routes.rb
Rails.application.routes.draw do
  resources :words
  root 'single_page_apps#type_words'
  get  '/math', to: 'single_page_apps#math_quiz'
  get  '/backup', to: 'words#backup'
  get  '/restore', to: 'words#restore'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
  has_one_attached :sound
  has_one_attached :video

  validates :name, presence: true
  validates :sound, presence: true, blob: { content_type: :audio }
  validates :video, blob: { content_type: :video }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/single_page_apps_controller.rb
class SinglePageAppsController < ApplicationController
  def type_words
    @words = Word.all

    music_tracks = Dir["public/music_tracks/*.mp3"].map do |filename|

      {
        "path" => "/music_tracks/#{File.basename filename}",
        "name" => File.basename(filename)
      }
    end

    @server_data = {
      "music_tracks" => music_tracks
    }
  end

  def math_quiz
    word_sounds = Dir["public/math_sounds/*.mp3",
                      "public/math_sounds/*.m4a",
                      "public/math_sounds/*.wav",].map{ |filename|
      extension = File.extname(filename)
      word = File.basename(filename, extension) # remove extension
      {
        "word" => word,
        # ../ notation for assets in the pipeline, like sound files
        "sound_file" => "../math_sounds/#{File.basename filename}"
      }
    }


    goodjob_videos = Dir["public/math_sounds/*.mp4"].map{ |filename|
        # / notation for assets in the public folder, like videos
        "/math_sounds/#{File.basename filename}"
    }

    @server_data = {
      "word_sounds" => word_sounds,
      "goodjob_videos" => goodjob_videos
    }

  end
end

app/controllers/words_controller.rb
require 'streamio-ffmpeg'
require 'restore_from_files'

module WordsHelper

  # if the attached video is a .mov, convet it to mp4
  def ensure_video_is_mp4(word_object)
    if word_object.video.content_type != "video/mp4"
      word_object.video.open do |v|
        FFMPEG::Movie.new(v.path).transcode("tmp/transcoded.mp4")
        word_object.video.attach(
          io: File.open("tmp/transcoded.mp4"),
          filename: "#{word_object.name}.mp4")
      end
    end
  end

end

class WordsController < ApplicationController
  before_action :set_word, only: %i[ show edit update destroy ]

  # GET /words or /words.json
  def index
    @words = Word.all
  end

  # GET /words/1 or /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words or /words.json
  def create
    # convert movies to the correct format
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        helpers.ensure_video_is_mp4(@word)
        format.html { redirect_to @word, notice: "Word was successfully created." }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1 or /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        helpers.ensure_video_is_mp4(@word)
        format.html { redirect_to @word, notice: "Word was successfully updated." }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1 or /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: "Word was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # BACKUP ;) Save the records to disk in a human-readable way
  def backup

    # create backup path
    backup_root_path = File.join("backups/", "words")
    FileUtils.mkdir_p(backup_root_path)

    Word.all.each do |word|
      # create a folder with the word as its name
      word_folder = File.join(backup_root_path, word[:name])
      FileUtils.mkdir_p(word_folder)

      # and save the video and audio associated with it
      word.video.open do |f|
        new_video_filename = word.name + File.extname(f.path)
        FileUtils.cp(f.path, File.join(word_folder, new_video_filename))
      end
      word.sound.open do |f|
        new_sound_filename = word.name + File.extname(f.path)
        FileUtils.cp(f.path, File.join(word_folder, new_sound_filename))
      end # word.sound.open
    end # Word.all.each

    @backup_folder = File.join(backup_root_path, "**/*")
    @backup_contents = Dir.glob(@backup_folder)
  end

  def restore
    @output = restore_from_files()
    # render results
    @words = Word.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.require(:word).permit(:name, :sound, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/single_page_apps_helper.rb
module SinglePageAppsHelper

  def random_math_problem
    first_number = rand(1..10)
    second_number = rand(1..10)
    operator = ["+", "-"].sample
    if (operator == "-") and (first_number < second_number)
      foo = first_number
      first_number = second_number
      second_number = foo
    end

    return "#{first_number} #{operator} #{second_number} ="
  end

end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CelesteWords</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/single_page_apps/math_quiz.html.erb
<div data-controller="mathquiz"
	   data-action="keydown@document->mathquiz#registerKey"
	   data-mathquiz-serverdata-value=<%= @server_data.to_json %>
     >

	  <div data-action="click->mathquiz#gohome"
         id="mathquiz-back-button"
         class="big-button">BACK</div>

    <div id ="mathProblemDiv" >
        <span data-mathquiz-target="mathProblemSpan"><%= random_math_problem %></span>
        <span data-mathquiz-target="mathAnswerSpan" id="mathAnswerText"></span>
    </div>

	  <div id="videoDiv">
	      <video data-mathquiz-target="videoPlayer"
			         id = "videoPlayer"
			         src=""
			         type="video/mp4">
	      </video>
	  </div>

</div>

app/views/single_page_apps/type_words.html.erb
<div class="noscroll"
     data-controller="hello"
	   id="outerDiv"
	   data-action="keydown@document->hello#registerKey"
	   data-hello-serverdata-value=<%= URI.escape(@server_data.to_json) %>
	   data-hello-worddata-value=<%=
    @words.reduce(Hash.new){|old,new|
	  old.merge({
				  new[:name].upcase => {
							    name: new[:name].upcase,
								sound_url: url_for(new.sound),
								video_url: new.video.attached? ? url_for(new.video) : nil
							  }
				})
	}.to_json
		%>
	 >


	 <div data-hello-target="wordArea" id="wordArea">
	 </div>


	 <div data-hello-target="hintArea" id="hint-area">
	     <div data-action="click->hello#toggleHints" class="big-button" id="hint-button">HINT</div>
	   <div data-hello-target="hintCarousel" id="hint-carousel">
		 <% @words.select{|x| x.video.attached?}.each do |word| %>
		   <div data-hello-target="hint" class="hint-div">
			 <h3> <%= word[:name].upcase %> </h3>
			 <%= image_tag word.video.preview(resize_to_limit: [200, 200]) %>
			 <!-- more info on previews: https://guides.rubyonrails.org/active_storage_overview.html#previewing-files -->
		   </div>
		 <% end %>
	   </div>
	 </div>

	 <div id="videoDiv">
	   <video data-hello-target="videoPlayer"
			  id = "videoPlayer"
			  src=""
			  type="video/mp4">
	   </video>
	 </div>

</div>

app/views/words/_form.html.erb
<%= form_with(model: word) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
        <% word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/backup.html.erb
<p id="notice"><%= notice %></p>

<h1> Backup maybe complete </h1>

<p>
  <%= @backup_folder.to_s %>
</p>
<p>
  <%= @backup_contents.to_s %>
</p>

</div>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @word, local: true) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

	  <%= f.label :sound %>
      <%= f.file_field :sound, class: 'form-control' %>
	  
	  <%= f.label :video %>
      <%= f.file_field :video, class: 'form-control' %>

      <%= f.submit "Update Word", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>


<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<div class="scrollable">
    <h1>Words</h1>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @words.each do |word| %>
                <tr>
                    <td><%= word.name %></td>
                    <td><%= link_to 'Show', word %></td>
                    <td><%= link_to 'Edit', edit_word_path(word) %></td>
                    <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <br>

    <%= link_to 'New Word', new_word_path %>
</div>

app/views/words/new.html.erb
<h1>New Word</h1>

<div class="row scrollable">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @word, local: true) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

	  <%= f.label :sound %>
      <%= f.file_field :sound, class: 'form-control' %>

	  <%= f.label :video %>
      <%= f.file_field :video, class: 'form-control' %>

      <%= f.submit "Create Word", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/words/restore.html.erb
<p id="notice"><%= notice %></p>

<h1> Restore time. </h1>

<p>
    <%= @output.to_s %>
</p>
<p>
    I got these: <%= @words.to_a.to_s %>
</p>

</div>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>
<div class="scrollable">
    <div data-controller = "showword"
	       data-showword-soundpath-value=<%= url_for(@word.sound) %>
	  >

        <p>
	          <strong>Name:</strong>
	          <%= @word.name %>
        </p>

	      <button type="button" data-action="showword#playword">
	          Play Sound
	      </button>

	      <div>
            <% if @word.video.attached? %>
	              <video data-hello-target="videoElement"
			                 src=<%= url_for @word.video %>
			                 type="video/mp4"
			                 width="320"
			                 display=block
			                 controls
			          >
	              </video>
            <% else %>
                No video uploaded.
            <% end %> 
	      </div>

        <%= link_to 'Edit', edit_word_path(@word) %> |
        <%= link_to 'Back', words_path %>

    </div>
</div>